-- Smart Eco Bank: Supabase-only portfolio backend
-- Execute in Supabase SQL Editor using the postgres role.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  address text not null default '',
  avatar_url text,
  point_balance integer not null default 0 check (point_balance >= 0),
  green_level text not null default 'Eco Starter',
  total_gram_saved integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  latitude double precision not null,
  longitude double precision not null,
  is_open boolean not null default true,
  is_full boolean not null default false,
  open_info text not null default 'Buka hari ini',
  visitors_today integer not null default 0
);

create table if not exists public.rewards (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  point_cost integer not null check (point_cost > 0),
  category text not null default 'Lifestyle',
  stock integer not null default 0 check (stock >= 0),
  stock_max integer not null default 0,
  badge text,
  image text
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('deposit', 'redeem')),
  category text not null,
  weight_gram integer,
  points integer not null,
  status text not null default 'completed',
  location_id bigint references public.locations(id),
  location_name text,
  product_name text,
  reward_id bigint references public.rewards(id),
  qty integer,
  point_per_item integer,
  confidence numeric,
  ai_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  reference_type text not null default 'transaction',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.locations enable row level security;
alter table public.rewards enable row level security;
alter table public.transactions enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "profiles own" on public.profiles;
create policy "profiles own" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "locations readable" on public.locations;
create policy "locations readable" on public.locations for select using (true);
drop policy if exists "rewards readable" on public.rewards;
create policy "rewards readable" on public.rewards for select using (true);
drop policy if exists "transactions own" on public.transactions;
create policy "transactions own" on public.transactions for select using (auth.uid() = user_id);
drop policy if exists "notifications own" on public.notifications;
create policy "notifications own" on public.notifications for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.create_profile_for_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, phone, address)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'phone', ''),
    coalesce(new.raw_user_meta_data->>'address', '')
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.create_profile_for_user();

insert into public.profiles (id, full_name, phone, address)
select id, coalesce(raw_user_meta_data->>'full_name', ''), coalesce(raw_user_meta_data->>'phone', ''), coalesce(raw_user_meta_data->>'address', '')
from auth.users on conflict (id) do nothing;

create or replace function public.record_deposit(
  p_category text, p_product_name text, p_weight_gram integer,
  p_location_id bigint, p_confidence numeric default 88, p_message text default ''
) returns public.transactions language plpgsql security definer set search_path = public as $$
declare v_points integer := greatest(1, floor(p_weight_gram * 0.02)); v_tx public.transactions;
begin
  update public.profiles set point_balance = point_balance + v_points,
    total_gram_saved = total_gram_saved + p_weight_gram,
    green_level = case when total_gram_saved + p_weight_gram >= 10000 then 'Eco Champion' when total_gram_saved + p_weight_gram >= 3000 then 'Eco Warrior' else 'Eco Starter' end,
    updated_at = now() where id = auth.uid();
  insert into public.transactions (user_id,type,category,weight_gram,points,status,location_id,location_name,product_name,confidence,ai_message)
  select auth.uid(),'deposit',p_category,p_weight_gram,v_points,'completed',l.id,l.name,p_product_name,p_confidence,p_message from public.locations l where l.id=p_location_id returning * into v_tx;
  insert into public.notifications (user_id,title,body,reference_type) values (auth.uid(),'Poin berhasil ditambahkan','Setoran Anda menghasilkan ' || v_points || ' poin.','transaction');
  return v_tx;
end; $$;

create or replace function public.redeem_reward(p_reward_id bigint, p_quantity integer default 1)
returns integer language plpgsql security definer set search_path = public as $$
declare v_reward public.rewards; v_cost integer; v_balance integer;
begin
  select * into v_reward from public.rewards where id=p_reward_id for update;
  if v_reward.id is null or v_reward.stock < p_quantity then raise exception 'Reward tidak tersedia'; end if;
  v_cost := v_reward.point_cost * p_quantity;
  select point_balance into v_balance from public.profiles where id=auth.uid() for update;
  if coalesce(v_balance,0) < v_cost then raise exception 'Poin tidak cukup'; end if;
  update public.profiles set point_balance=point_balance-v_cost, updated_at=now() where id=auth.uid();
  update public.rewards set stock=stock-p_quantity where id=p_reward_id;
  insert into public.transactions (user_id,type,category,points,status,product_name,reward_id,qty,point_per_item)
  values (auth.uid(),'redeem',v_reward.category,-v_cost,'completed',v_reward.name,p_reward_id,p_quantity,v_reward.point_cost);
  insert into public.notifications (user_id,title,body,reference_type) values (auth.uid(),'Penukaran reward berhasil',v_reward.name || ' sedang diproses.','reward');
  return v_balance-v_cost;
end; $$;

grant execute on function public.record_deposit(text,text,integer,bigint,numeric,text) to authenticated;
grant execute on function public.redeem_reward(bigint,integer) to authenticated;

insert into public.locations (name,address,latitude,longitude,open_info,visitors_today)
select * from (values
  ('Bank Sampah Induk Surabaya','Jl. Raya Menur No. 28, Surabaya',-7.2654,112.7612,'Buka 08.00–16.00',18),
  ('Eco Drop Point Tunjungan','Jl. Tunjungan No. 1, Surabaya',-7.2575,112.7521,'Buka 09.00–20.00',9),
  ('Bank Sampah Hijau','Jl. Darmo Permai, Surabaya',-7.2918,112.7037,'Buka 08.00–15.00',12)
) as seed(name,address,latitude,longitude,open_info,visitors_today)
where not exists (select 1 from public.locations);

insert into public.rewards (name,description,point_cost,category,stock,stock_max,badge)
select * from (values
  ('Tumbler Ramah Lingkungan','Tumbler stainless untuk penggunaan sehari-hari.',500,'Lifestyle',25,25,'Populer'),
  ('Voucher Belanja Rp10.000','Voucher digital untuk belanja kebutuhan harian.',750,'Voucher',30,30,null),
  ('Tas Belanja Daur Ulang','Tas belanja kuat berbahan material daur ulang.',1000,'Lifestyle',15,15,'Eco Choice')
) as seed(name,description,point_cost,category,stock,stock_max,badge)
where not exists (select 1 from public.rewards);
